/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityTimeline: typeof import('./components/ActivityTimeline.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AuthDialog: typeof import('./components/AuthDialog.vue')['default']
    BreadcrumbNav: typeof import('./components/BreadcrumbNav.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    CollabChat: typeof import('./components/CollabChat.vue')['default']
    CollabCursors: typeof import('./components/CollabCursors.vue')['default']
    CollabToolbar: typeof import('./components/CollabToolbar.vue')['default']
    CommentList: typeof import('./components/CommentList.vue')['default']
    CreateProjectFab: typeof import('./components/CreateProjectFab.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    JudgeDetail: typeof import('./components/JudgeDetail.vue')['default']
    LoadingSkeleton: typeof import('./components/LoadingSkeleton.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    MiniChart: typeof import('./components/MiniChart.vue')['default']
    MobileNav: typeof import('./components/MobileNav.vue')['default']
    OAuthButtons: typeof import('./components/OAuthButtons.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    ProjectCardEnhanced: typeof import('./components/ProjectCardEnhanced.vue')['default']
    ProjectPreview: typeof import('./components/ProjectPreview.vue')['default']
    RouteLoadingBar: typeof import('./components/RouteLoadingBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchPreview: typeof import('./components/ScratchPreview.vue')['default']
    ScratchPreviewDialog: typeof import('./components/ScratchPreviewDialog.vue')['default']
    ShareDialog: typeof import('./components/ShareDialog.vue')['default']
    VirtualList: typeof import('./components/VirtualList.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
