JWT_SECRET=4pnwzc8sQwT4phTslBU/x/IIJeZFowTShugTvcwaigEIJN/+aDxcyMwJ2ZHC15cdYUatHj56FKWPwCNXQb/gew=
JWT_REFRESH_SECRET=8MtYwFm3YrIfPaaLTT3PBzBTznJ93+rBjiml8D65584jmkZtFQdtO1VpDS/fla1cw7MOyYySWAvzjlH08Aq7lg==
JWT_EXPIRATION=3600000
